#--------------------------------------------------------
#GitHub Action AWS Lambda Deploy
#-------------------------------------------------------
name: Lambda-Deploy
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-java@v4
         with:
          java-version: '17'
          distribution: 'temurin'
       - name: Java vesion test
         run: java --version
       - name: Run the Maven verify phase
         run: mvn --batch-mode --update-snapshots package
       - name: Run command ls -la
         run: ls -la
       
       

